var appConstants = {

    CHANGE_FILTER_TEXT: 'CHANGE_FILTER_TEXT',
    SORT_BY_TITLE: 'SORT_BY_TITLE',
    SORT_BY_IMAGE: 'SORT_BY_IMAGE',
    SORT_BY_VIEWS: 'SORT_BY_VIEWS',
    SORT_BY_CREATED: 'SORT_BY_CREATED',
    CHANGE_SORT_BY_OPTION: 'CHANGE_SORT_BY_OPTION',
    UPDATE_SORT_STATUS: 'UPDATE_SORT_STATUS',
    GET_VIDEOS: 'GET_VIDEOS',
    CHANGE_SEARCH_QUERY: 'CHANGE_SEARCH_QUERY'

};

module.exports = appConstants;
